[menus]
    [[menus.main]]
        name = 'Strona główna'
        pageRef = '/'
        weight = 1
    [[menus.main]]
        name = 'Benchmarki'
        pageRef = '/benchmarks'
        weight = 4
    [[menus.main]]
        name = 'Poradniki'
        pageRef = '/guides'
        weight = 3
    [[menus.main]]
        name = 'Posty'
        pageRef = '/posts'
        weight = 2
    [[menus.main]]
        name = 'O mnie'
        pageRef = '/about'
        weight = 5