[[main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 2
[[main]]
    name = 'Guides'
    pageRef = '/guides'
    weight = 4
[[main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 3
[[main]]
    name = 'About me'
    pageRef = '/about'
    weight = 5

[[socials]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/maciej-%C5%9Blusarz-5a4804200'