baseURL = 'https://example.org/'
title = 'Maciej Ślusarz'

[languages]
    [languages.en]
        disabled = false
        languageCode = 'en'
        languageName = 'English'
        weight = 1
    [languages.pl]
        disabled = false
        languageCode = 'pl-PL'
        languageName = 'Polish'
        weight = 2