baseURL = 'https://example.org/'
title = 'Maciej Ślusarz'
defaultContentLanguage = 'en'

[languages]
    [languages.en]
        disabled = false
        languageCode = 'en'
        languageName = 'English'
        weight = 1
    [languages.pl]
        disabled = false
        languageCode = 'pl-PL'
        languageName = 'Polski'
        weight = 2

[imaging]
    quality = 75